# Generated by Django 4.2.6 on 2023-10-21 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="uploaded_file",
            new_name="file",
        ),
    ]
