# Generated by Django 4.2.6 on 2023-10-21 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0002_rename_uploaded_file_files_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Files",
            new_name="File",
        ),
    ]
