# Generated by Django 4.2.6 on 2023-10-23 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0005_alter_file_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_id",
            field=models.UUIDField(default=uuid.UUID("1d291339-3442-4f38-a5d0-d9f6386837b9")),
        ),
    ]
