# Generated by Django 4.2.6 on 2023-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcriber", "0006_alter_file_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_id",
            field=models.UUIDField(),
        ),
    ]
